# Generated by Django 5.0.6 on 2024-05-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='01', editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
