# Generated by Django 5.0.6 on 2024-05-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0002_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
    ]
