# Generated by Django 5.0.6 on 2024-05-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0003_alter_job_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='01', editable=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
