# Generated by Django 5.0.6 on 2024-05-16 15:51

import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0005_jobsearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsearch',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='state',
            field=localflavor.us.models.USStateField(default='1', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='level',
            field=models.CharField(blank=True, choices=[('1', 'Internship'), ('2', 'Entry-level'), ('3', 'Associate'), ('4', 'Mid-Senior'), ('5', 'Director'), ('6', 'Executive')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='recency',
            field=models.CharField(blank=True, choices=[('r86400', 'Past day'), ('r604800', 'Past week'), ('r2592000', 'Past month'), ('', 'Any time')], max_length=10, null=True),
        ),
    ]
