# Generated by Django 5.0.6 on 2024-05-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0008_job_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Applied'), ('2', 'Initial Contact'), ('3', 'Completed Phone Screen')], max_length=2, null=True),
        ),
    ]
