# Generated by Django 5.0.6 on 2024-05-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0010_job_about_job_co_link_job_company_size_job_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='about',
            new_name='details',
        ),
    ]
