# Generated by Django 5.0.6 on 2024-06-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0011_rename_about_job_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsearch',
            name='level',
        ),
        migrations.RemoveField(
            model_name='jobsearch',
            name='recency',
        ),
        migrations.RemoveField(
            model_name='jobsearch',
            name='workplace_type',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Considering'), ('2', 'Applied'), ('3', 'Initial Contact'), ('4', 'Completed Phone Screen'), ('0', 'Not interested')], max_length=2, null=True),
        ),
    ]
