# Generated by Django 5.0.6 on 2024-06-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0013_alter_job_company_alter_job_location_alter_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='co_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
