# Generated by Django 5.0.6 on 2024-06-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0014_alter_job_co_link_alter_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
