# Generated by Django 5.0.6 on 2024-07-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0018_remove_job_company_company_importer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
