# Generated by Django 5.0.6 on 2024-07-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0019_company_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['importer_name']},
        ),
        migrations.RemoveField(
            model_name='company',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='company',
            name='importer_name',
            field=models.CharField(help_text='Must match the key from the importer', max_length=255, verbose_name='Name'),
        ),
    ]
