# Generated by Django 5.0.6 on 2024-07-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0021_group_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-50', '1-50 employees'), ('51-200', '51-200 employees')], max_length=20, null=True),
        ),
    ]
