# Generated by Django 5.0.6 on 2024-07-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0022_alter_company_company_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='agencies',
            field=models.ManyToManyField(blank=True, null=True, to='jobsearch.agency'),
        ),
    ]
