# Generated by Django 5.0.6 on 2024-07-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0023_agency_company_about_company_agencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='affiliations',
            field=models.ManyToManyField(blank=True, to='jobsearch.group'),
        ),
        migrations.AlterField(
            model_name='company',
            name='agencies',
            field=models.ManyToManyField(blank=True, to='jobsearch.agency'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-50', '1-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1,000 employees')], max_length=20, null=True),
        ),
    ]
