# Generated by Django 5.0.6 on 2024-07-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0025_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('engineering', 'Engineering and Data'), ('product', 'Product'), ('design', 'Design and Research'), ('content', 'Content'), ('delivery', 'Delivery'), ('bd', 'Business Development'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
