# Generated by Django 5.0.6 on 2024-09-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0026_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('office', 'Back Office'), ('bd', 'Business Development'), ('content', 'Content'), ('data', 'Data and Analytics'), ('delivery', 'Delivery'), ('design', 'Design and Research'), ('engineering', 'Engineering and Development'), ('marketing', 'Marketing and Communications'), ('product', 'Product Management'), ('security', 'Security'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
