# Generated by Django 5.0.6 on 2024-09-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0027_job_featured_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('office', 'Back Office'), ('bd', 'Business Development'), ('content', 'Content & Communications'), ('data', 'Data and Analytics'), ('delivery', 'Delivery'), ('design', 'Design and Research'), ('engineering', 'Engineering & Development'), ('help', 'Help and Support'), ('product', 'Product Management'), ('security', 'Security'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
