# Generated by Django 5.0.6 on 2026-06-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0028_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='classification',
            field=models.CharField(blank=True, choices=[('leading_practice', 'leading_practice'), ('demonstrated_practice', 'demonstrated_practice'), ('limited_evidence', 'limited_evidence')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='delivery_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='evaluation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='evaluation_evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='evaluation_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='framework_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reputation_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='service_maturity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='viability_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
