# Generated by Django 5.0.6 on 2026-06-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0029_company_classification_company_delivery_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='classification',
        ),
    ]
